# Generated by Django 4.0.1 on 2022-01-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=50)),
                ('cat_Name', models.CharField(default='', max_length=200)),
                ('cat_img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img', models.ImageField(upload_to='media')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_description', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.categories')),
            ],
        ),
    ]
